sun: layers.StringLookUp
sun: layers.IntegerLookUp

In [10]:
import tensorflow as tf
from keras import layers 
import pandas as pd

## layers.StringLookUp

In [11]:
vocab = ["a", "b", "c", "d"]
data = tf.constant([["a", "c", "d"], ["d", "z", "b"]])
layer = layers.StringLookup(vocabulary=vocab)
print(layer.get_vocabulary())
print(layer(data))

['[UNK]', 'a', 'b', 'c', 'd']
tf.Tensor(
[[1 3 4]
 [4 0 2]], shape=(2, 3), dtype=int64)


In [12]:
#dataframe = pd.read_csv('../../data/feature_data.csv')
#dataframe.head()

In [13]:
#labels = dataframe.pop('label')
#ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
#ds = ds.shuffle(buffer_size=len(dataframe))
#ds = ds.batch(5)
#ds = ds.prefetch(5)

#[(train_features, label_batch)] = ds.take(1)
#print('Every feature:', list(train_features.keys()))
#print('A batch of school_type:', train_features['school_type'])
#print('A batch of label:', label_batch )

## layers.IntegerLookUp

In [14]:
vocab = [0, 1, 2]
data = tf.constant([[3, 0, 1], [2, 4, 1]])
layer = layers.IntegerLookup(vocabulary=vocab)
print(layer.get_vocabulary())
print(layer(data))

[-1, 0, 1, 2]
tf.Tensor(
[[0 1 2]
 [3 0 2]], shape=(2, 3), dtype=int64)
