sun: tf.expand_dim
sun: tf.reduce_sum
sun: tf.tensordot

In [11]:
import tensorflow as tf

## tf.expand_dim

In [12]:
# 生成形状为 [5, 3] 的，元素为 0 到 9 的浮点数随机张量
random_float_tensor = tf.random.uniform(shape=[5, 3], minval=0, maxval=10)
# 将浮点数随机张量转换为整数
random_int_tensor = tf.cast(random_float_tensor, tf.int32)
print(random_int_tensor)

tf.Tensor(
[[9 7 7]
 [3 8 9]
 [0 3 1]
 [9 9 4]
 [4 2 5]], shape=(5, 3), dtype=int32)


In [13]:
tf.expand_dims(random_int_tensor, axis=0)

<tf.Tensor: shape=(1, 5, 3), dtype=int32, numpy=
array([[[9, 7, 7],
        [3, 8, 9],
        [0, 3, 1],
        [9, 9, 4],
        [4, 2, 5]]])>

In [14]:
tf.expand_dims(random_int_tensor, axis=1)

<tf.Tensor: shape=(5, 1, 3), dtype=int32, numpy=
array([[[9, 7, 7]],

       [[3, 8, 9]],

       [[0, 3, 1]],

       [[9, 9, 4]],

       [[4, 2, 5]]])>

In [15]:
tf.expand_dims(random_int_tensor, axis=-1)

<tf.Tensor: shape=(5, 3, 1), dtype=int32, numpy=
array([[[9],
        [7],
        [7]],

       [[3],
        [8],
        [9]],

       [[0],
        [3],
        [1]],

       [[9],
        [9],
        [4]],

       [[4],
        [2],
        [5]]])>

## tf.reduce_sum

In [16]:
# 缩减所有的维度，并返回具有单个元素的张量（缩减求和）
print(random_int_tensor)
print(tf.reduce_sum(random_int_tensor))

tf.Tensor(
[[9 7 7]
 [3 8 9]
 [0 3 1]
 [9 9 4]
 [4 2 5]], shape=(5, 3), dtype=int32)
tf.Tensor(80, shape=(), dtype=int32)


In [17]:
# 在0维度上进行求和, (5, 3) -> (3,)
print(tf.reduce_sum(random_int_tensor, 0))

tf.Tensor([25 29 26], shape=(3,), dtype=int32)


In [18]:
# 在1维度上求和，(5, 3) -> (5,)
print(tf.reduce_sum(random_int_tensor, 1))

tf.Tensor([23 20  4 22 11], shape=(5,), dtype=int32)


## tf.tensordot

In [19]:
a = tf.constant([1, 2, 3])
b = tf.constant([3, 4, 5])
print(tf.tensordot(a, b, axes=1))

tf.Tensor(26, shape=(), dtype=int32)


In [20]:
a = tf.constant([[1, 2, 3], 
                 [4, 5, 6]])
b = tf.constant([[4, 5, 6], 
                [7, 8, 9]])
# (2 * 3) * (3 * 2) :最后一个维度相乘，最后结果是：(2 * 2)
print(tf.tensordot(a, tf.transpose(b), axes=1)) 

tf.Tensor(
[[ 32  50]
 [ 77 122]], shape=(2, 2), dtype=int32)


## tensor做运算

In [21]:
# 定义两个张量
tensor1 = tf.constant([[1, 2], 
                       [3, 4]])
tensor2 = tf.constant([[5, 6], 
                       [7, 8]])
tensor3 = tf.constant([9, 10])


# 使用 tf.multiply() 函数进行相乘
result1 = tf.multiply(tensor1, tensor2)
result2 = tf.subtract(tensor1, tensor2)

# 或者直接使用 * 运算符
result1 = tensor1 * tensor2
result2 = tensor1 - tensor2
result3 = tensor1 + tensor3
# 打印结果
print(result1)
print(result2)
print(result3)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 12]
 [12 14]], shape=(2, 2), dtype=int32)


In [22]:
keys = tf.keras.Input(shape=(50, 32), name='keys')
print(keys.shape)
input = tf.keras.Input(shape=(32,), name='input')  # (none, 32)
input_shape = tf.keras.backend.int_shape(input) # (none, 32)
print(input_shape)
print(len(input_shape))
print('--------------------------------------')
## input数据每一个样本: [1, 2, 3, .....]  reshape后每一个样本：1个特征，每个特征32维 [[1,2,3,4,5,6 ...]]
input_reshape = tf.reshape(input, shape=[-1, 1, 32])
print(input_reshape)   ## (none, 1, 32)

input_tile = tf.tile(input_reshape, multiples=[1, 50, 1])
print(input_tile)    ## (none, 50, 32)  这个操作在特征上扩展了50倍啊 。变成了从[[1,2,3...],[1,2,3...]....]
# 做减法，形状不变
print(input_tile - keys) ## (none, 50, 32)
print(input_tile * keys) ## (none, 50, 32)

(None, 50, 32)
(None, 32)
2
--------------------------------------


ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```

What you should do instead is wrap `tf_fn` in a layer:

```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```
