In [1]:
import tensorflow as tf

## tf.expand_dim

In [2]:
# 生成形状为 [5, 3] 的，元素为 0 到 9 的浮点数随机张量
random_float_tensor = tf.random.uniform(shape=[5, 3], minval=0, maxval=10)
# 将浮点数随机张量转换为整数
random_int_tensor = tf.cast(random_float_tensor, tf.int32)
print(random_int_tensor)

tf.Tensor(
[[6 7 8]
 [4 2 4]
 [1 1 1]
 [9 7 5]
 [5 2 5]], shape=(5, 3), dtype=int32)


In [3]:
tf.expand_dims(random_int_tensor, axis=0)

<tf.Tensor: shape=(1, 5, 3), dtype=int32, numpy=
array([[[6, 7, 8],
        [4, 2, 4],
        [1, 1, 1],
        [9, 7, 5],
        [5, 2, 5]]], dtype=int32)>

In [4]:
tf.expand_dims(random_int_tensor, axis=1)

<tf.Tensor: shape=(5, 1, 3), dtype=int32, numpy=
array([[[6, 7, 8]],

       [[4, 2, 4]],

       [[1, 1, 1]],

       [[9, 7, 5]],

       [[5, 2, 5]]], dtype=int32)>

In [5]:
tf.expand_dims(random_int_tensor, axis=-1)

<tf.Tensor: shape=(5, 3, 1), dtype=int32, numpy=
array([[[6],
        [7],
        [8]],

       [[4],
        [2],
        [4]],

       [[1],
        [1],
        [1]],

       [[9],
        [7],
        [5]],

       [[5],
        [2],
        [5]]], dtype=int32)>