sun: tf.expand_dim
sun: tf.reduce_sum

In [2]:
import tensorflow as tf

## tf.expand_dim

In [3]:
# 生成形状为 [5, 3] 的，元素为 0 到 9 的浮点数随机张量
random_float_tensor = tf.random.uniform(shape=[5, 3], minval=0, maxval=10)
# 将浮点数随机张量转换为整数
random_int_tensor = tf.cast(random_float_tensor, tf.int32)
print(random_int_tensor)

tf.Tensor(
[[5 3 9]
 [4 3 3]
 [5 8 7]
 [3 4 6]
 [3 7 3]], shape=(5, 3), dtype=int32)


In [4]:
tf.expand_dims(random_int_tensor, axis=0)

<tf.Tensor: shape=(1, 5, 3), dtype=int32, numpy=
array([[[5, 3, 9],
        [4, 3, 3],
        [5, 8, 7],
        [3, 4, 6],
        [3, 7, 3]]])>

In [5]:
tf.expand_dims(random_int_tensor, axis=1)

<tf.Tensor: shape=(5, 1, 3), dtype=int32, numpy=
array([[[5, 3, 9]],

       [[4, 3, 3]],

       [[5, 8, 7]],

       [[3, 4, 6]],

       [[3, 7, 3]]])>

In [6]:
tf.expand_dims(random_int_tensor, axis=-1)

<tf.Tensor: shape=(5, 3, 1), dtype=int32, numpy=
array([[[5],
        [3],
        [9]],

       [[4],
        [3],
        [3]],

       [[5],
        [8],
        [7]],

       [[3],
        [4],
        [6]],

       [[3],
        [7],
        [3]]])>

## tf.reduce_sum

In [11]:
# 缩减所有的维度，并返回具有单个元素的张量（缩减求和）
print(random_int_tensor)
print(tf.reduce_sum(random_int_tensor))

tf.Tensor(
[[5 3 9]
 [4 3 3]
 [5 8 7]
 [3 4 6]
 [3 7 3]], shape=(5, 3), dtype=int32)
tf.Tensor(73, shape=(), dtype=int32)


In [9]:
# 在0维度上进行求和, (5, 3) -> (3,)
print(tf.reduce_sum(random_int_tensor, 0))

tf.Tensor([20 25 28], shape=(3,), dtype=int32)


In [10]:
# 在1维度上求和，(5, 3) -> (5,)
print(tf.reduce_sum(random_int_tensor, 1))

tf.Tensor([17 10 20 13 13], shape=(5,), dtype=int32)
