In [2]:
import tensorflow as tf

In [5]:
# (2, 3)
t1 = tf.constant([[1, 2, 3], [4, 5, 6]]) 
print(tf.repeat(t1, 4, 1))
# (2, 1, 3)
e_t1 = tf.expand_dims(t1, 1)
print(e_t1)
# (2, 4, 3)
print(tf.repeat(e_t1, 4, 1))

tf.Tensor(
[[1 1 1 1 2 2 2 2 3 3 3 3]
 [4 4 4 4 5 5 5 5 6 6 6 6]], shape=(2, 12), dtype=int32)
tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]], shape=(2, 1, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]
  [4 5 6]]], shape=(2, 4, 3), dtype=int32)
